version: "3"
services:
  docs:
    build: .                 # 用上面的 Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./:/work
    working_dir: /work/mysite
    command: serve -a 0.0.0.0:8000