name: deploy
on:
  push:
    branches: [ main ]
permissions:
  contents: write
jobs:
  gh-pages:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: mysite
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
      - run: pip install mkdocs-material mkdocs-awesome-pages-plugin mkdocs-exclude mkdocs-minify-plugin mkdocs-git-revision-date-localized-plugin
      - run: mkdocs gh-deploy --force