name: deploy
on:
  push:
    branches: [ main ]
permissions:
  contents: write
jobs:
  gh-pages:
    runs-on: ubuntu-latest
    container:
      image: squidfunk/mkdocs-material:latest
    defaults:
      run:
        working-directory: mysite
    steps:
      - uses: actions/checkout@v4
      - run: pip install mkdocs-awesome-pages-plugin mkdocs-exclude mkdocs-minify-plugin mkdocs-git-revision-date-localized-plugin
      - run: mkdocs gh-deploy --force